leftnav:
- identifier: 65e9a26c-7eb5-15dd-cc2b-917aabc8edeb
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: d6a5b285-94a6-7559-ee63-2fe328583dc2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 51f735ac-8c2c-ecfe-c956-0abad555a549
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 71d84178-cb81-565a-fb72-896685022491
  name: Lecture Slides
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 92ed03f4-ac78-0804-719a-106c33b18018
  name: Assignments
  pageRef: /pages/assignments/
  weight: 50
- identifier: 9304597a-9612-3cee-baf2-e092268c98eb
  name: 'Paper #1'
  pageRef: /pages/assignments/paper-1
  parent: 92ed03f4-ac78-0804-719a-106c33b18018
  weight: 60
- identifier: 87861921-e77c-53b2-7a2f-421288527df5
  name: 'Paper #2'
  pageRef: /pages/assignments/paper-2
  parent: 92ed03f4-ac78-0804-719a-106c33b18018
  weight: 70
- identifier: 0b6a9bad-19cb-a069-a915-9b14a8c0beff
  name: 'Paper #3'
  pageRef: /pages/assignments/paper-3
  parent: 92ed03f4-ac78-0804-719a-106c33b18018
  weight: 80
- identifier: 9063d62b-9aa1-2b0a-1af0-a9513892453e
  name: Criteria & Guidelines for Papers
  pageRef: /pages/assignments/criteria-guidelines-for-papers
  parent: 92ed03f4-ac78-0804-719a-106c33b18018
  weight: 90
- identifier: a78b49df-d3ea-0bf3-b227-8d62f42de555
  name: Study Materials
  pageRef: /pages/studymaterials
  weight: 100
